trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET 9 Preview SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true
  displayName: 'Install .NET 9 SDK (Preview)'

# Restore Dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'backend/backend.csproj'
    arguments: '--verbosity detailed'
  displayName: 'Restore Dependencies'

# Build Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'backend/backend.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Build Project'

# Publish Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'backend/backend.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
    zipAfterPublish: true
  displayName: 'Publish Project'

# Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'backend-artifact'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
